"""CI gate: fail on hand-typed, unmarked accuracy-shaped numbers in tracked docs.

Why this exists: README.md and site/*.html drifted out of sync with the real eval gate
three separate times (85% vs the real 83% threshold, prompt v2.0/v2.1 vs the real v2.3,
"tiered routing OFF" vs the real ON) because accuracy numbers were hand-typed in prose
instead of generated from eval/results/latest.json. See docs/architecture/adr/0001-*.md.

What this checks: every tracked `*.md` / `*.html` file (excluding EXCLUDED_PATH_PREFIXES /
EXCLUDED_EXACT_FILES below) for percentage-shaped tokens (`83.8%`, `85%`, ...) that appear
near an accuracy-flavored keyword (accuracy/precision/recall/f1/gate/threshold/overall) --
either on the same line, in a small prose window, or inside the same Markdown/HTML table --
UNLESS that number sits inside one of two recognised marker blocks:

  <!-- METRICS:START:<block-name> --> ... <!-- METRICS:END -->
      Owned and regenerated by scripts/render_metrics.py from the eval JSON. A second CI
      step diffs the generator's output against the committed file (drift check) -- see
      .github/workflows/ci.yml. This is the actual single-source-of-truth mechanism.

  <!-- METRICS:HISTORICAL --> ... <!-- /METRICS:HISTORICAL -->
      A frozen historical measurement (a past release's numbers, a Roadmap bullet
      describing what was true when a phase shipped). NOT regenerated or drift-checked --
      this only tells the scanner "a human reviewed this, it's an intentional historical
      record, not a live claim that can silently drift." Do not use this to dodge the
      real fix; use it only for numbers that are genuinely frozen-in-time.

LIMITATION -- read before trusting this check: this is a regex heuristic, not a parser.
It is tuned to this repo's actual history (verified against every existing tracked
*.md/*.html file when written) to keep the false-positive rate low, not to be a
general-purpose classifier of "is this an accuracy claim." Known gaps: it can't see
percentages embedded in code spans/blocks as distinct from prose (a `50%` in a fenced
code example reads the same as prose); it uses fixed keyword proximity windows, so a
result reported far from any keyword in a large prose block could be missed. Treat this
as "catches the class of bug we've had three times," not "catches every possible one."
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Paths excluded wholesale, with the reason inline. Keep this list short and each entry
# justified -- it's the thing that keeps this check honest instead of a rubber stamp.
EXCLUDED_PATH_PREFIXES: tuple[str, ...] = (
    "benchmark/",  # generated report artifacts (commit c344b92) -- not hand-typed
    "eval/report.md",  # regenerated every eval/runner.py run by eval/report.py
    "eval/fixtures/",  # per-fixture creation-time verification notes, not live claims
    "eval/data/",  # fixture sourcing documentation, no accuracy claims
    "ops/runbooks/",  # operational thresholds (billing/traffic/storage %), not model accuracy
    "docs/architecture/adr/",  # ADRs are point-in-time decision records, immutable once accepted
)
EXCLUDED_EXACT_FILES: frozenset[str] = frozenset(
    {
        "plan.md",  # living execution tracker -- dated history by design (rule 20)
        "plan_v1.md",  # superseded planning doc, historical record
        "review-iq-closeout-roadmap.md",  # historical roadmap, dated entries
        "PROMPTS.md",  # prompt changelog -- dated historical eval deltas per version
        "spec.md",  # task-scoped spec doc for a bounded past experiment, historical
    }
)

GENERATED_BLOCK_RE = re.compile(
    r"<!--\s*METRICS:START(?::[\w.-]+)?\s*-->.*?<!--\s*METRICS:END\s*-->", re.DOTALL
)
HISTORICAL_BLOCK_RE = re.compile(
    r"<!--\s*METRICS:HISTORICAL\s*-->.*?<!--\s*/METRICS:HISTORICAL\s*-->", re.DOTALL
)
PERCENT_RE = re.compile(r"\b\d{1,3}(?:\.\d+)?\s?%")
KEYWORD_RE = re.compile(r"\b(accuracy|precision|recall|f1|gate|threshold|overall)\b", re.IGNORECASE)
TABLE_ROW_RE = re.compile(r"^\s*\|")

# Prose window: how many lines before/after a non-table hit to search for a keyword.
PROSE_WINDOW = 2


def _tracked_md_and_html_files() -> list[Path]:
    """Return tracked *.md/*.html files under the repo, via `git ls-files`."""
    result = subprocess.run(
        ["git", "ls-files", "*.md", "*.html"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return [REPO_ROOT / p for p in result.stdout.splitlines() if p.strip()]


def _is_excluded(rel_path: str) -> bool:
    if rel_path in EXCLUDED_EXACT_FILES:
        return True
    return any(rel_path.startswith(prefix) for prefix in EXCLUDED_PATH_PREFIXES)


def _blank_out(pattern: re.Pattern[str], text: str) -> str:
    """Replace every match of `pattern` with an equal number of newlines.

    Preserves line numbers so later reporting still points at the right source line,
    while making sure nothing inside the matched span can trip the scan.
    """
    return pattern.sub(lambda m: "\n" * m.group(0).count("\n"), text)


def _markdown_table_block(lines: list[str], idx: int) -> str:
    """Return the contiguous `|...|` block containing line `idx`, joined as one string."""
    start = idx
    while start > 0 and TABLE_ROW_RE.match(lines[start - 1]):
        start -= 1
    end = idx
    while end < len(lines) - 1 and TABLE_ROW_RE.match(lines[end + 1]):
        end += 1
    return "\n".join(lines[start : end + 1])


def _html_table_block(text: str, match_pos: int) -> str:
    """Return the enclosing <table>...</table> block for a match at `match_pos`, or ''."""
    open_idx = text.rfind("<table", 0, match_pos)
    if open_idx == -1:
        return ""
    close_idx = text.find("</table>", match_pos)
    if close_idx == -1:
        close_idx = len(text)
    return text[open_idx:close_idx]


def find_violations(path: Path) -> list[tuple[int, str]]:
    """Return [(1-based line number, line text), ...] for unmarked accuracy-shaped numbers."""
    raw = path.read_text(encoding="utf-8")
    text = _blank_out(HISTORICAL_BLOCK_RE, _blank_out(GENERATED_BLOCK_RE, raw))
    lines = text.splitlines()
    is_html = path.suffix == ".html"

    violations: list[tuple[int, str]] = []
    offset = 0
    for i, line in enumerate(lines):
        for m in PERCENT_RE.finditer(line):
            if is_html:
                context = _html_table_block(text, offset + m.start())
                if not context:
                    context = "\n".join(lines[max(0, i - PROSE_WINDOW) : i + PROSE_WINDOW + 1])
            elif TABLE_ROW_RE.match(line):
                context = _markdown_table_block(lines, i)
            else:
                context = "\n".join(lines[max(0, i - PROSE_WINDOW) : i + PROSE_WINDOW + 1])

            if KEYWORD_RE.search(context):
                violations.append((i + 1, line.strip()))
                break  # one flag per line is enough
        offset += len(line) + 1  # +1 for the '\n' splitlines() consumed

    return violations


def main() -> int:
    any_violations = False
    for path in _tracked_md_and_html_files():
        rel = path.relative_to(REPO_ROOT).as_posix()
        if _is_excluded(rel) or not path.exists():
            continue
        violations = find_violations(path)
        if violations:
            any_violations = True
            print(f"\n{rel}:")
            for line_no, line_text in violations:
                print(f"  line {line_no}: {line_text}")

    if any_violations:
        print(
            "\nFAIL: hand-typed accuracy-shaped numbers found outside a "
            "<!-- METRICS:START/END --> generated block or a <!-- METRICS:HISTORICAL --> "
            "frozen-record block.\n"
            "Fix by either: (a) sourcing the number from eval/results/latest.json via "
            "scripts/render_metrics.py inside a METRICS:START/END block, (b) wrapping a "
            "genuinely frozen historical figure in METRICS:HISTORICAL markers, or "
            "(c) if the whole file is out of scope (generated report, unrelated %), add it "
            "to EXCLUDED_PATH_PREFIXES/EXCLUDED_EXACT_FILES above with a one-line reason.",
            file=sys.stderr,
        )
        return 1

    print("OK: no unmarked accuracy-shaped numbers found in tracked Markdown/HTML.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
